// apps/interface/src/components/ui/LoadingButton.tsx
import type { AsyncOrSync } from "ts-essentials";
import Button from "@components/ui/button";
import { useState, type ReactNode } from "react";

interface Props {
    children?: ReactNode;
    onclick?: () => AsyncOrSync<unknown>;
    // any props that come into the component
    variant?: string
    style?: string
    loading?: boolean
}

function LoadingButton({children, onclick, ...props}: Props) {
    let [loading, setLoading] = useState(false);

    return <Button {...props}
        loading={props.loading || loading}
        onclick={async () => {
            setLoading(true);
            try {
                if (onclick) {
                    await onclick();
                }
            } catch (e) {
                console.error(e);
                throw e;
            } finally {
                setLoading(false);
            }
        }
    }>
        {children}
    </Button>
}

export default LoadingButton

// packages/ui/src/lib/components/LoadingButton.svelte
<script lang="ts">
  import type { ComponentProps } from "svelte";
  import type { AsyncOrSync } from "ts-essentials";
  import { toast } from "./toast";
  import { Button } from "./ui/button";

  let {
    children,
    onclick,
    ...props
  }: ComponentProps<Button> & {
    onclick: () => AsyncOrSync<unknown>;
  } = $props();

  let loading = $state(false);
</script>

<Button
  {...props}
  loading={props.loading || loading}
  onclick={async () => {
    loading = true;
    try {
      await onclick();
    } catch (e) {
      toast.error(e);
      throw e;
    } finally {
      loading = false;
    }
  }}
>
  {@render children?.()}
</Button>
