// src/components/auth/Query.tsx
import { castArray } from "lodash-es";
import { useEffect } from "react";
import type { ArrayOrSingle } from "ts-essentials";

interface Props {
    query:
      | {
          status: "pending";
        }
      | {
          status: "error";
          error: any;
        }
      | {
          status: "success";
          data: any;
        };
    hide?: ArrayOrSingle<"pending" | "error">;
    error?: any;
    pending?: any;
    success: any;
}


function Query({
    query,
    hide = [],
    error,
    pending,
    success,
  }: Props) {
  
    useEffect(() => {
        if (query.status === "error") {
            console.error(query.error);
          }
    }, [query])

  let hideArray = castArray(hide);

  if (query.status === "pending") {
    if (!hideArray.includes("pending")) {
        if (pending) {
            return <p>Pending</p>
        } else {
            return <p>Loading...</p>
        }
    }
  } else if (query.status === "error") {
    if (!hideArray.includes("error")) {
        if (error) {
            return <p>{query.error}</p>
        } else {
            return <p>Error: nothing</p>
        }
    }
  } else if (query.status === "success") {
    return <p>{query.data}</p>
  }
}

export default Query;

// packages/ui/src/lib/components/Query.svelte
<script lang="ts" generics="T, E">
  import { castArray } from "lodash-es";
  import type { Snippet } from "svelte";
  import type { ArrayOrSingle } from "ts-essentials";

  let {
    query,
    hide = [],
    error,
    pending,
    success,
  }: {
    query:
      | {
          status: "pending";
        }
      | {
          status: "error";
          error: E;
        }
      | {
          status: "success";
          data: T;
        };
    hide?: ArrayOrSingle<"pending" | "error">;
    error?: Snippet<[E]>;
    pending?: Snippet;
    success: Snippet<[T]>;
  } = $props();

  $effect(() => {
    if (query.status === "error") {
      console.error(query.error);
    }
  });

  let hideArray = $derived(castArray(hide));
</script>

{#if query.status === "pending"}
  {#if !hideArray.includes("pending")}
    {#if pending}
      {@render pending()}
    {:else}
      Loading...
    {/if}
  {/if}
{:else if query.status === "error"}
  {#if !hideArray.includes("error")}
    {#if error}
      {@render error(query.error)}
    {:else}
      Error: {String(query.error)}
    {/if}
  {/if}
{:else if query.status === "success"}
  {@render success(query.data)}
{/if}
