// packages/ui/src/lib/components/GapContainer.svelte
<script lang="ts">
  import { cn } from "#lib/utils.js";
  import type { HTMLAttributes } from "svelte/elements";
  let { children, ...props }: HTMLAttributes<HTMLDivElement> = $props();
</script>

<div {...props} class={cn("flex flex-col gap-6", props.class)}>
  {@render children?.()}
</div>

// src/components/auth/GapContainer.tsx
import type { ReactNode } from "react";

interface Props {
    children?: ReactNode
    // any props that come into the component
}

function GapContainer({children}: Props) {
    return <div className="flex flex-col gap-2">
        {children}
    </div>
}

export default GapContainer;
